#!/bin/bash
# /etc/init.d/interactive-player

### BEGIN INIT INFO
# Provides:          interactive-player
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts interactive player app
# Description:       This service is used to start the interactive player
### END INIT INFO


case "$1" in
	start)
		echo "Starting interactive-player"
		/home/pi/interactive-player/bin/interactive-player
		;;
	stop)
		echo "Stopping interactive-player"
		killall interactive-player
		;;
	*)
		echo "Usage: /etc/init.d/interactive-player start|stop"
		exit 1
		;;
esac

exit 0
